query GetMetricBreakdown(
    $desktopAppExperienceId: String!
    $dimensionToGroupBy: DesktopAppGroupByDimensionInput!
    $timeFrameFilter: DesktopAppTimeframeFilterInput!
    $dimensionsFilterExcludingCurrentBreakdown: DesktopAppDimensionsFilterInput!
    $orderBy: DesktopAppBreakdownOrderingInput
    $limit: Int!
  ) {
    desktopAppExperience(id: $desktopAppExperienceId) {
      metricBreakdown(
        dimensionToGroupBy: $dimensionToGroupBy
        timeFrameFilter: $timeFrameFilter
        dimensionsFilter: $dimensionsFilterExcludingCurrentBreakdown
        orderBy: $orderBy
        limit: $limit
      ) {
        breakdownKey
        countEmployees
        crashesPerEmployee
        employeesWithCrashes
        avgNetResponseTimeMs
        failedConnectionsRatio
      }
    }
  }
