query GetRemoteAction($uuid: String!) {
    remoteActionByUId(uid: $uuid) {
      uuid # queried for support / debug purposes, not to be used in UI
      contentId # queried for ARM calls support / debug purposes, not to be used in UI
      ...RemoteAction
    }
  }


  fragment RemoteAction on RemoteAction {
    id
    name
    origin
    title
    contentType
    productArea
    description
    purpose
    targeting {
      ...Targeting
    }
    targetingEntity {
      ...TargetingEntity
    }
    scheduledTasks {
      ...ScheduledTask
    }
    scriptInfo {
      ...ScriptInfo
    }
  }


  fragment Targeting on Targeting {
    manualEnabled
    apiEnabled
    manualAllowMultipleDevices
    schedulingEnabled
    endPointSchedulingEnabled
    workflowEnabled
    sparkEnabled
  }


  fragment TargetingEntity on TargetingEntity {
    deviceEnabled
    vdiSessionEnabled
    vdiSessionTargeting
    allowUserOverrideVDISessionTargeting
  }


  fragment ScheduledTask on ScheduledTask {
    inputs {
      ...ScheduledTaskInput
    }
    name
    nqlQuery
    scheduleType
    uuid
    cron
    timeZone
  }


  fragment ScheduledTaskInput on InputValue {
    id
    value
  }


  fragment ScriptInfo on ScriptInfo {
    inputs {
      ...ScriptInfoInput
    }
    outputs {
      ...ScriptInfoOutput
    }
    runAs
    scriptMacOs {
      ...Script
    }
    scriptWindows {
      ...Script
    }
    timeoutSeconds
    executionServiceDelegate
  }


  fragment ScriptInfoInput on Input {
    allowCustomValue
    description
    id
    name
    options
    usedByMacOs
    usedByWindows
  }


  fragment ScriptInfoOutput on Output {
    description
    id
    name
    type
    usedByMacOs
    usedByWindows
  }


  fragment Script on Script {
    name
    script
  }
