package ai_tools

const (
	EndpointList                     = "/apigateway/aidex/config/v2/aitools/application"
	EndpointGet                      = "/apigateway/aidex/config/v2/aitools/application"
	EndpointCreate                   = "/apigateway/aidex/config/v2/aitools/application"
	EndpointUpdate                   = "/apigateway/aidex/config/v2/aitools/application"
	EndpointDelete                   = "/apigateway/aidex/config/v2/aitools/application"
	EndpointGetCopilot               = "/apigateway/aidex/config/v2/aitools/ms-copilot"
	EndpointCreateCopilot            = "/apigateway/aidex/config/v2/aitools/ms-copilot"
	EndpointUpdateCopilot            = "/apigateway/aidex/config/v2/aitools/ms-copilot"
	EndpointDeleteCopilot            = "/apigateway/aidex/config/v2/aitools/ms-copilot"
	EndpointListGoals                = "/apigateway/aidex/config/v1/goal"
	EndpointGetGoal                  = "/apigateway/aidex/config/v1/goal"
	EndpointCreateGoal               = "/apigateway/aidex/config/v1/goal"
	EndpointUpdateGoal               = "/apigateway/aidex/config/v1/goal"
	EndpointDeleteGoal               = "/apigateway/aidex/config/v1/goal"
	EndpointGetLegacyTool            = "/apigateway/aidex/config/v1/tool"
	EndpointListSystemTools          = "/apigateway/aidex/config/v1/tool/system-tools"
	EndpointGetLicense               = "/apigateway/aidex/config/v1/aitools/license"
	EndpointGetRedirectURLs          = "/apigateway/aidex/config/v1/tool/redirect-urls"
	EndpointGetModule                = "/apigateway/aidex/config/v1/module"
	EndpointCreateModule             = "/apigateway/aidex/config/v1/module"
	EndpointUpdateModule             = "/apigateway/aidex/config/v1/module"
	EndpointCheckCopilotCredentials  = "/apigateway/aidex/check-credentials/ms-copilot"
	EndpointGetOverviewInsights      = "/apigateway/aidex/insights/overview"
	EndpointGetToolInsights          = "/apigateway/aidex/insights/tool"
	EndpointGetGovernanceTrends      = "/apigateway/aidex/insights/observability/governance/tool-governance-trends"
	EndpointGetGovernanceActiveUsers = "/apigateway/aidex/insights/observability/governance/tool-governance-active-users"
	EndpointGetGovernanceDashboard   = "/apigateway/aidex/insights/observability/governance/tool-governance-dashboard"
	EndpointGetGoalInsights          = "/apigateway/aidex/goals/v1/goals"
)
